
package com.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentInterfaceImp", targetNamespace = "http://webservice_student_server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentInterfaceImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "studentQuery", targetNamespace = "http://webservice_student_server/", className = "com.webservice.client.StudentQuery")
    @ResponseWrapper(localName = "studentQueryResponse", targetNamespace = "http://webservice_student_server/", className = "com.webservice.client.StudentQueryResponse")
    @Action(input = "http://webservice_student_server/StudentInterfaceImp/studentQueryRequest", output = "http://webservice_student_server/StudentInterfaceImp/studentQueryResponse")
    public String studentQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
